POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ninichuexpress@gmail.com",
  "password": "droEjIu2.123"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "connor.urbano.mendoza@gmail.com",
  "password": "droEjIu2.123"
}
